image: microsoft/dotnet:sdk
stages:
    - compile
    - test
    - publish

compile api:
    stage: compile
    script:
        - 'dotnet restore'
        - 'dotnet build'

test: 
    stage: test
    script:
        - 'dotnet test keepnote-step6-boilerplat/test/Test.csproj'

publish auth api:
    stage: publish
    script:
        - 'dotnet publish  keepnote-step6-boilerplate/AuthenticationService/AuthenticationService.csproj -c Release'
    artifacts:
        paths:
            - /JesalRajendra.Shah/Final_Demo/keepnote-step6-boilerplate/AuthenticationService/bin/Release/netcoreapp2.2/AuthenticationService.dll
        expire_in: 1 week




