image: microsoft/dotnet:sdk
stages:
    - compile
    - publish

compile api:
    stage: compile
    script:
        - 'dotnet restore keepnote-step6-boilerplate'
        - 'dotnet build keepnote-step6-boilerplate'

publish auth api:
    stage: publish
    script:
        - 'dotnet publish keepnote-step6-boilerplate/AuthenticationService/AuthenticationService.csproj -c Release'
    artifacts:
        paths:
            - /JesalRajendra.Shah/Final_Demo/keepnote-step6-boilerplate/AuthenticationService/bin/Release/netcoreapp2.2/AuthenticationService.dll
        expire_in: 1 week




